name: Delete PR Env
on:
  pull_request:
    types:
      - closed

env:
  APP_NAME: jaytest101
  ENVIRONMENT_ID: pr-${{ github.event.number }}
  HUMCTL_VERSION: '0.25.0'


jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: humanitec/setup-cli-action@v1
        with:
          version: ${{ env.HUMCTL_VERSION }}
      - name: Delete Humanitec Env
        run: |
          humctl delete env ${{ env.ENVIRONMENT_ID }} \
              --token ${{ secrets.HUMANITEC_TOKEN }} \
              --org ${{ vars.HUMANITEC_ORG_ID }} \
              --app ${{ env.APP_NAME }}


